# Generated by Django 4.0.8 on 2026-10-04 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_essayquestion_options_and_more'),
        ('course', '0007_alter_upload_file_submission_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='submission',
            name='one_submission_per_student',
        ),
        migrations.AddField(
            model_name='submission',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='quiz.quiz'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('course', 'student', 'quiz'), name='one_submission_per_student_and_quiz'),
        ),
    ]
