# Generated by Django 4.0.8 on 2026-10-04 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_remove_submission_one_submission_per_student_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='submission',
            name='one_submission_per_student_and_quiz',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='quiz',
        ),
        migrations.AddField(
            model_name='submission',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='course.upload', verbose_name='Actividad'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('course', 'student', 'document'), name='one_submission_per_student_and_document'),
        ),
    ]
