# Generated by Django 4.0.8 on 2026-10-04 17:11

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_remove_submission_one_submission_per_student_and_quiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='feedback',
            field=models.TextField(blank=True, verbose_name='Comentarios'),
        ),
        migrations.AddField(
            model_name='submission',
            name='graded_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='mark',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('10'))], verbose_name='Nota'),
        ),
        migrations.AddField(
            model_name='upload',
            name='is_activity',
            field=models.BooleanField(default=False, help_text='El alumno puede entregar su ejercicio de esta actividad.', verbose_name='Actividad'),
        ),
        migrations.AddField(
            model_name='upload',
            name='is_evaluable',
            field=models.BooleanField(default=False, help_text='Solo las actividades evaluables cuentan para la nota final.', verbose_name='Actividad evaluable'),
        ),
    ]
