# Generated by Django 4.0.8 on 2026-10-06 17:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_alter_upload_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Valid Files: pdf, docx, doc, odt, html, xls, xlsx, ppt, pptx, zip, rar, 7zip', upload_to='course_files/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'doc', 'odt', 'html', 'xls', 'xlsx', 'ppt', 'pptx', 'zip', 'rar', '7zip'])])),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='course.upload')),
            ],
            options={
                'verbose_name': 'Fichero adicional',
                'verbose_name_plural': 'Ficheros adicionales',
            },
        ),
    ]
